version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/home/node/app 
    ports:
      - 3000:3000
#    depends_on:
#      - db
      
  # db:
  #   image:      mongo:5.0.5
  #   restart:    always
  #   volumes:
  #     - ./.docker/dbdata:/data/db
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_ROOT_DATABASE=analytics
    

  # #// e’ a interface de web para poder gerenciar o mongo
  # mongo-express:
  #   image: mongo-express:0.54.0
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=db #// nome do container na corrente linha 19 
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root #// autenticacao
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root #// usuario administrativo
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  #   depends_on:
  #     - db

